import useApp from "@data/hooks/UseApp"
import Head from 'next/head'

export default function PageHead({ title }) {
    const { shop } = useApp()
    return (
        <>
            <Head>
                <title>{`${shop?.name} - ${title}`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    )
}